env: {
    browser: true,
    es2021: true,
  }
   preLoaders: 
    [
      {
        exclude: /node_modules/,
        loader: 'eslint-loader',
        options: {
          fix: true,
          quiet: true,
          failOnError: true,
        },
      },
    ]
  extends: [
    'plugin:react/recommended',
    'airbnb',
  ]
  overrides: [
  ]
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  }
  plugins: [
    'react',
  ]
  rules: {
    'no-param-reassign': 0,
  }
